import './globals.css'

// import "@fontsource-variable/noto-sans-jp/wght.css";
import "@fontsource/noto-sans-jp/400.css";
import "@fontsource/noto-sans-jp/800.css";

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata = {
  title: '地球が何回回った時？',
  description: 'Generated by create next app',
  colorScheme: 'dark',
  themeColor: '#0f172a',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    viewportFit: 'cover',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja" className="dark">
    <body>{children}</body>
    </html>
  )
}
